name = "adwaita"

main_bg.r = 246
main_bg.g = 245
main_bg.b = 244
main_fg.r = 46
main_fg.g = 52
main_fg.b = 54
title.r = 46
title.g = 52
title.b = 54
hi_fg.r = 26
hi_fg.g = 95
hi_fg.b = 180
selected_bg.r = 28
selected_bg.g = 113
selected_bg.b = 216
selected_fg.r = 255
selected_fg.g = 255
selected_fg.b = 255
inactive_fg.r = 94
inactive_fg.g = 92
inactive_fg.b = 100
div_line.r = 46
div_line.g = 52
div_line.b = 54
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
menu_fg.r = 46
menu_fg.g = 52
menu_fg.b = 54
menu_selected_bg.r = 28
menu_selected_bg.g = 113
menu_selected_bg.b = 216
menu_selected_fg.r = 26
menu_selected_fg.g = 95
menu_selected_fg.b = 180

