name = "adwaita"

main_bg.r = 246
main_bg.g = 245
main_bg.b = 244
main_fg.r = 46
main_fg.g = 52
main_fg.b = 54
title.r = 46
title.g = 52
title.b = 54
hi_fg.r = 26
hi_fg.g = 95
hi_fg.b = 180
selected_bg.r = 28
selected_bg.g = 113
selected_bg.b = 216
selected_fg.r = 255
selected_fg.g = 255
selected_fg.b = 255
inactive_fg.r = 94
inactive_fg.g = 92
inactive_fg.b = 100
div_line.r = 46
div_line.g = 52
div_line.b = 54
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 46
search_box.g = 52
search_box.b = 54
log_box.r = 61
log_box.g = 60
log_box.b = 20
player_box.r = 46
player_box.g = 52
player_box.b = 54
menu_bg.r = 246
menu_bg.g = 245
menu_bg.b = 244
menu_fg.r = 46
menu_fg.g = 52
menu_fg.b = 54
menu_selected_bg.r = 28
menu_selected_bg.g = 113
menu_selected_bg.b = 216
menu_selected_fg.r = 26
menu_selected_fg.g = 95
menu_selected_fg.b = 180
gradient_start.r = 26
gradient_start.g = 95
gradient_start.b = 180
gradient_mid.r = 26
gradient_mid.g = 95
gradient_mid.b = 180
gradient_end.r = 192
gradient_end.g = 28
gradient_end.b = 40

