name = "adwaita-dark"

main_bg.r = 29
main_bg.g = 29
main_bg.b = 29
main_fg.r = 222
main_fg.g = 221
main_fg.b = 218
title.r = 222
title.g = 221
title.b = 218
hi_fg.r = 98
hi_fg.g = 160
hi_fg.b = 234
selected_bg.r = 28
selected_bg.g = 113
selected_bg.b = 216
selected_fg.r = 255
selected_fg.g = 255
selected_fg.b = 255
inactive_fg.r = 119
inactive_fg.g = 118
inactive_fg.b = 123
div_line.r = 119
div_line.g = 118
div_line.b = 123
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 119
search_box.g = 118
search_box.b = 123
log_box.r = 119
log_box.g = 118
log_box.b = 123
player_box.r = 119
player_box.g = 118
player_box.b = 123
menu_bg.r = 29
menu_bg.g = 29
menu_bg.b = 29
menu_fg.r = 222
menu_fg.g = 221
menu_fg.b = 218
menu_selected_bg.r = 28
menu_selected_bg.g = 113
menu_selected_bg.b = 216
menu_selected_fg.r = 98
menu_selected_fg.g = 160
menu_selected_fg.b = 234
gradient_start.r = 98
gradient_start.g = 160
gradient_start.b = 234
gradient_mid.r = 28
gradient_mid.g = 113
gradient_mid.b = 216
gradient_end.r = 224
gradient_end.g = 27
gradient_end.b = 36

