name = "ayu"

main_bg.r = 11
main_bg.g = 14
main_bg.b = 20
main_fg.r = 191
main_fg.g = 189
main_fg.b = 182
title.r = 191
title.g = 189
title.b = 182
hi_fg.r = 230
hi_fg.g = 180
hi_fg.b = 80
selected_bg.r = 230
selected_bg.g = 180
selected_bg.b = 80
selected_fg.r = 248
selected_fg.g = 248
selected_fg.b = 242
inactive_fg.r = 86
inactive_fg.g = 91
inactive_fg.b = 102
div_line.r = 86
div_line.g = 91
div_line.b = 102
graph_text.r = 191
graph_text.g = 189
graph_text.b = 182
meter_bg.r = 86
meter_bg.g = 91
meter_bg.b = 102
search_box.r = 223
search_box.g = 191
search_box.b = 255
log_box.r = 149
log_box.g = 230
log_box.b = 203
player_box.r = 230
player_box.g = 182
player_box.b = 115
menu_bg.r = 11
menu_bg.g = 14
menu_bg.b = 20
menu_fg.r = 191
menu_fg.g = 189
menu_fg.b = 182
menu_selected_bg.r = 230
menu_selected_bg.g = 180
menu_selected_bg.b = 80
menu_selected_fg.r = 230
menu_selected_fg.g = 180
menu_selected_fg.b = 80
gradient_start.r = 223
gradient_start.g = 191
gradient_start.b = 255
gradient_mid.r = 210
gradient_mid.g = 166
gradient_mid.b = 255
gradient_end.r = 163
gradient_end.g = 122
gradient_end.b = 204

