name = "default"

main_bg.r = 10
main_bg.g = 22
main_bg.b = 40
main_fg.r = 200
main_fg.g = 215
main_fg.b = 225
title.r = 240
title.g = 250
title.b = 255
hi_fg.r = 79
hi_fg.g = 195
hi_fg.b = 247
selected_bg.r = 20
selected_bg.g = 50
selected_bg.b = 80
selected_fg.r = 128
selected_fg.g = 222
selected_fg.b = 234
inactive_fg.r = 67
inactive_fg.g = 103
inactive_fg.b = 127
div_line.r = 42
div_line.g = 102
div_line.b = 161
graph_text.r = 100
graph_text.g = 165
graph_text.b = 195
menu_fg.r = 144
menu_fg.g = 164
menu_fg.b = 174
menu_selected_bg.r = 20
menu_selected_bg.g = 50
menu_selected_bg.b = 80
menu_selected_fg.r = 128
menu_selected_fg.g = 222
menu_selected_fg.b = 234

