name = "dracula"

main_bg.r = 40
main_bg.g = 42
main_bg.b = 54
main_fg.r = 248
main_fg.g = 248
main_fg.b = 242
title.r = 248
title.g = 248
title.b = 242
hi_fg.r = 98
hi_fg.g = 114
hi_fg.b = 164
selected_bg.r = 255
selected_bg.g = 121
selected_bg.b = 198
selected_fg.r = 248
selected_fg.g = 248
selected_fg.b = 242
inactive_fg.r = 68
inactive_fg.g = 71
inactive_fg.b = 90
div_line.r = 68
div_line.g = 71
div_line.b = 90
graph_text.r = 248
graph_text.g = 248
graph_text.b = 242
meter_bg.r = 68
meter_bg.g = 71
meter_bg.b = 90
search_box.r = 189
search_box.g = 147
search_box.b = 249
log_box.r = 80
log_box.g = 250
log_box.b = 123
player_box.r = 139
player_box.g = 233
player_box.b = 253
menu_bg.r = 40
menu_bg.g = 42
menu_bg.b = 54
menu_fg.r = 248
menu_fg.g = 248
menu_fg.b = 242
menu_selected_bg.r = 255
menu_selected_bg.g = 121
menu_selected_bg.b = 198
menu_selected_fg.r = 98
menu_selected_fg.g = 114
menu_selected_fg.b = 164
gradient_start.r = 189
gradient_start.g = 147
gradient_start.b = 249
gradient_mid.r = 255
gradient_mid.g = 121
gradient_mid.b = 198
gradient_end.r = 255
gradient_end.g = 51
gradient_end.b = 168

