name = "dracula"

main_bg.r = 40
main_bg.g = 42
main_bg.b = 54
main_fg.r = 248
main_fg.g = 248
main_fg.b = 242
title.r = 248
title.g = 248
title.b = 242
hi_fg.r = 98
hi_fg.g = 114
hi_fg.b = 164
selected_bg.r = 255
selected_bg.g = 121
selected_bg.b = 198
selected_fg.r = 61
selected_fg.g = 61
selected_fg.b = 60
inactive_fg.r = 109
inactive_fg.g = 114
inactive_fg.b = 144
div_line.r = 109
div_line.g = 114
div_line.b = 144
graph_text.r = 248
graph_text.g = 248
graph_text.b = 242
menu_fg.r = 248
menu_fg.g = 248
menu_fg.b = 242
menu_selected_bg.r = 255
menu_selected_bg.g = 121
menu_selected_bg.b = 198
menu_selected_fg.r = 98
menu_selected_fg.g = 114
menu_selected_fg.b = 164

