name = "dusklight"

main_bg.r = 4
main_bg.g = 20
main_bg.b = 46
main_fg.r = 153
main_fg.g = 223
main_fg.b = 255
title.r = 153
title.g = 255
title.b = 255
hi_fg.r = 255
hi_fg.g = 127
hi_fg.b = 0
selected_bg.r = 114
selected_bg.g = 43
selected_bg.b = 1
selected_fg.r = 153
selected_fg.g = 255
selected_fg.b = 255
inactive_fg.r = 5
inactive_fg.g = 46
inactive_fg.b = 81
div_line.r = 165
div_line.g = 88
div_line.b = 0
graph_text.r = 121
graph_text.g = 161
graph_text.b = 180
meter_bg.r = 5
meter_bg.g = 46
meter_bg.b = 81
search_box.r = 0
search_box.g = 255
search_box.b = 255
log_box.r = 0
log_box.g = 255
log_box.b = 255
player_box.r = 0
player_box.g = 255
player_box.b = 255
menu_bg.r = 4
menu_bg.g = 20
menu_bg.b = 46
menu_fg.r = 153
menu_fg.g = 223
menu_fg.b = 255
menu_selected_bg.r = 114
menu_selected_bg.g = 43
menu_selected_bg.b = 1
menu_selected_fg.r = 255
menu_selected_fg.g = 127
menu_selected_fg.b = 0
gradient_start.r = 0
gradient_start.g = 173
gradient_start.b = 255
gradient_mid.r = 0
gradient_mid.g = 255
gradient_mid.b = 255
gradient_end.r = 255
gradient_end.g = 248
gradient_end.b = 107

