name = "dusklight"

main_bg.r = 4
main_bg.g = 20
main_bg.b = 46
main_fg.r = 153
main_fg.g = 223
main_fg.b = 255
title.r = 153
title.g = 255
title.b = 255
hi_fg.r = 255
hi_fg.g = 127
hi_fg.b = 0
selected_bg.r = 114
selected_bg.g = 43
selected_bg.b = 1
selected_fg.r = 153
selected_fg.g = 255
selected_fg.b = 255
inactive_fg.r = 5
inactive_fg.g = 46
inactive_fg.b = 81
div_line.r = 165
div_line.g = 88
div_line.b = 0
graph_text.r = 121
graph_text.g = 161
graph_text.b = 180
menu_fg.r = 153
menu_fg.g = 223
menu_fg.b = 255
menu_selected_bg.r = 114
menu_selected_bg.g = 43
menu_selected_bg.b = 1
menu_selected_fg.r = 255
menu_selected_fg.g = 127
menu_selected_fg.b = 0

