name = "elementarish"

main_bg.r = 51
main_bg.g = 51
main_bg.b = 51
main_fg.r = 238
main_fg.g = 232
main_fg.b = 213
title.r = 238
title.g = 232
title.b = 213
hi_fg.r = 209
hi_fg.g = 48
hi_fg.b = 44
selected_bg.r = 38
selected_bg.g = 138
selected_bg.b = 208
selected_fg.r = 238
selected_fg.g = 232
selected_fg.b = 213
inactive_fg.r = 101
inactive_fg.g = 123
inactive_fg.b = 131
div_line.r = 101
div_line.g = 123
div_line.b = 131
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 101
search_box.g = 123
search_box.b = 131
log_box.r = 101
log_box.g = 123
log_box.b = 131
player_box.r = 101
player_box.g = 123
player_box.b = 131
menu_bg.r = 51
menu_bg.g = 51
menu_bg.b = 51
menu_fg.r = 238
menu_fg.g = 232
menu_fg.b = 213
menu_selected_bg.r = 38
menu_selected_bg.g = 138
menu_selected_bg.b = 208
menu_selected_fg.r = 209
menu_selected_fg.g = 48
menu_selected_fg.b = 44
gradient_start.r = 133
gradient_start.g = 153
gradient_start.b = 0
gradient_mid.r = 178
gradient_mid.g = 134
gradient_mid.b = 2
gradient_end.r = 209
gradient_end.g = 48
gradient_end.b = 44

