name = "elementarish"

main_bg.r = 51
main_bg.g = 51
main_bg.b = 51
main_fg.r = 238
main_fg.g = 232
main_fg.b = 213
title.r = 238
title.g = 232
title.b = 213
hi_fg.r = 233
hi_fg.g = 54
hi_fg.b = 49
selected_bg.r = 38
selected_bg.g = 138
selected_bg.b = 208
selected_fg.r = 0
selected_fg.g = 0
selected_fg.b = 0
inactive_fg.r = 105
inactive_fg.g = 128
inactive_fg.b = 136
div_line.r = 105
div_line.g = 128
div_line.b = 136
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
menu_fg.r = 238
menu_fg.g = 232
menu_fg.b = 213
menu_selected_bg.r = 38
menu_selected_bg.g = 138
menu_selected_bg.b = 208
menu_selected_fg.r = 209
menu_selected_fg.g = 48
menu_selected_fg.b = 44

