name = "everforest-light-medium"

main_bg.r = 253
main_bg.g = 246
main_bg.b = 227
main_fg.r = 92
main_fg.g = 106
main_fg.b = 114
title.r = 92
title.g = 106
title.b = 114
hi_fg.r = 223
hi_fg.g = 105
hi_fg.b = 186
selected_bg.r = 79
selected_bg.g = 88
selected_bg.b = 94
selected_fg.r = 223
selected_fg.g = 160
selected_fg.b = 0
inactive_fg.r = 157
inactive_fg.g = 169
inactive_fg.b = 160
div_line.r = 79
div_line.g = 88
div_line.b = 94
graph_text.r = 92
graph_text.g = 106
graph_text.b = 114
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 79
search_box.g = 88
search_box.b = 94
log_box.r = 79
log_box.g = 88
log_box.b = 94
player_box.r = 79
player_box.g = 88
player_box.b = 94
menu_bg.r = 253
menu_bg.g = 246
menu_bg.b = 227
menu_fg.r = 92
menu_fg.g = 106
menu_fg.b = 114
menu_selected_bg.r = 79
menu_selected_bg.g = 88
menu_selected_bg.b = 94
menu_selected_fg.r = 223
menu_selected_fg.g = 105
menu_selected_fg.b = 186
gradient_start.r = 141
gradient_start.g = 161
gradient_start.b = 1
gradient_mid.r = 223
gradient_mid.g = 160
gradient_mid.b = 0
gradient_end.r = 248
gradient_end.g = 85
gradient_end.b = 82

