name = "everforest-dark-hard"

main_bg.r = 39
main_bg.g = 46
main_bg.b = 51
main_fg.r = 211
main_fg.g = 198
main_fg.b = 170
title.r = 211
title.g = 198
title.b = 170
hi_fg.r = 230
hi_fg.g = 126
hi_fg.b = 128
selected_bg.r = 55
selected_bg.g = 65
selected_bg.b = 69
selected_fg.r = 219
selected_fg.g = 188
selected_fg.b = 127
inactive_fg.r = 102
inactive_fg.g = 120
inactive_fg.b = 133
div_line.r = 102
div_line.g = 121
div_line.b = 128
graph_text.r = 211
graph_text.g = 198
graph_text.b = 170
menu_fg.r = 211
menu_fg.g = 198
menu_fg.b = 170
menu_selected_bg.r = 55
menu_selected_bg.g = 65
menu_selected_bg.b = 69
menu_selected_fg.r = 230
menu_selected_fg.g = 126
menu_selected_fg.b = 128

