name = "everforest-light-medium"

main_bg.r = 253
main_bg.g = 246
main_bg.b = 227
main_fg.r = 92
main_fg.g = 106
main_fg.b = 114
title.r = 92
title.g = 106
title.b = 114
hi_fg.r = 216
hi_fg.g = 102
hi_fg.b = 180
selected_bg.r = 79
selected_bg.g = 88
selected_bg.b = 94
selected_fg.r = 255
selected_fg.g = 255
selected_fg.b = 255
inactive_fg.r = 135
inactive_fg.g = 145
inactive_fg.b = 137
div_line.r = 79
div_line.g = 88
div_line.b = 94
graph_text.r = 92
graph_text.g = 106
graph_text.b = 114
menu_fg.r = 92
menu_fg.g = 106
menu_fg.b = 114
menu_selected_bg.r = 79
menu_selected_bg.g = 88
menu_selected_bg.b = 94
menu_selected_fg.r = 223
menu_selected_fg.g = 105
menu_selected_fg.b = 186

