name = "everforest-dark-medium"

main_bg.r = 45
main_bg.g = 53
main_bg.b = 59
main_fg.r = 211
main_fg.g = 198
main_fg.b = 170
title.r = 211
title.g = 198
title.b = 170
hi_fg.r = 230
hi_fg.g = 126
hi_fg.b = 128
selected_bg.r = 61
selected_bg.g = 72
selected_bg.b = 77
selected_fg.r = 219
selected_fg.g = 188
selected_fg.b = 127
inactive_fg.r = 108
inactive_fg.g = 127
inactive_fg.b = 141
div_line.r = 109
div_line.g = 128
div_line.b = 137
graph_text.r = 211
graph_text.g = 198
graph_text.b = 170
menu_fg.r = 211
menu_fg.g = 198
menu_fg.b = 170
menu_selected_bg.r = 61
menu_selected_bg.g = 72
menu_selected_bg.b = 77
menu_selected_fg.r = 230
menu_selected_fg.g = 126
menu_selected_fg.b = 128

