name = "everforest-dark-hard"

main_bg.r = 39
main_bg.g = 46
main_bg.b = 51
main_fg.r = 211
main_fg.g = 198
main_fg.b = 170
title.r = 211
title.g = 198
title.b = 170
hi_fg.r = 230
hi_fg.g = 126
hi_fg.b = 128
selected_bg.r = 55
selected_bg.g = 65
selected_bg.b = 69
selected_fg.r = 219
selected_fg.g = 188
selected_fg.b = 127
inactive_fg.r = 39
inactive_fg.g = 46
inactive_fg.b = 51
div_line.r = 55
div_line.g = 65
div_line.b = 69
graph_text.r = 211
graph_text.g = 198
graph_text.b = 170
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 55
search_box.g = 65
search_box.b = 69
log_box.r = 55
log_box.g = 65
log_box.b = 69
player_box.r = 55
player_box.g = 65
player_box.b = 69
menu_bg.r = 39
menu_bg.g = 46
menu_bg.b = 51
menu_fg.r = 211
menu_fg.g = 198
menu_fg.b = 170
menu_selected_bg.r = 55
menu_selected_bg.g = 65
menu_selected_bg.b = 69
menu_selected_fg.r = 230
menu_selected_fg.g = 126
menu_selected_fg.b = 128
gradient_start.r = 167
gradient_start.g = 192
gradient_start.b = 128
gradient_mid.r = 219
gradient_mid.g = 188
gradient_mid.b = 127
gradient_end.r = 248
gradient_end.g = 85
gradient_end.b = 82

