name = "flat-remix-light"

main_bg.r = 228
main_bg.g = 228
main_bg.b = 231
main_fg.r = 115
main_fg.g = 118
main_fg.b = 128
title.r = 39
title.g = 42
title.b = 52
hi_fg.r = 136
hi_fg.g = 136
hi_fg.b = 136
selected_bg.r = 184
selected_bg.g = 23
selected_bg.b = 76
selected_fg.r = 136
selected_fg.g = 136
selected_fg.b = 136
inactive_fg.r = 136
inactive_fg.g = 136
inactive_fg.b = 136
div_line.r = 136
div_line.g = 136
div_line.b = 136
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
menu_fg.r = 115
menu_fg.g = 118
menu_fg.b = 128
menu_selected_bg.r = 184
menu_selected_bg.g = 23
menu_selected_bg.b = 76
menu_selected_fg.r = 136
menu_selected_fg.g = 136
menu_selected_fg.b = 136

