name = "flat-remix-light"

main_bg.r = 228
main_bg.g = 228
main_bg.b = 231
main_fg.r = 115
main_fg.g = 118
main_fg.b = 128
title.r = 39
title.g = 42
title.b = 52
hi_fg.r = 136
hi_fg.g = 136
hi_fg.b = 136
selected_bg.r = 184
selected_bg.g = 23
selected_bg.b = 76
selected_fg.r = 136
selected_fg.g = 136
selected_fg.b = 136
inactive_fg.r = 136
inactive_fg.g = 136
inactive_fg.b = 136
div_line.r = 136
div_line.g = 136
div_line.b = 136
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 54
search_box.g = 123
search_box.b = 240
log_box.r = 25
log_box.g = 161
log_box.b = 135
player_box.r = 74
player_box.g = 174
player_box.b = 230
menu_bg.r = 228
menu_bg.g = 228
menu_bg.b = 231
menu_fg.r = 115
menu_fg.g = 118
menu_fg.b = 128
menu_selected_bg.r = 184
menu_selected_bg.g = 23
menu_selected_bg.b = 76
menu_selected_fg.r = 136
menu_selected_fg.g = 136
menu_selected_fg.b = 136
gradient_start.r = 54
gradient_start.g = 123
gradient_start.b = 240
gradient_mid.r = 184
gradient_mid.g = 23
gradient_mid.b = 76
gradient_end.r = 212
gradient_end.g = 25
gradient_end.b = 25

