name = "flexoki-light"

main_bg.r = 255
main_bg.g = 252
main_bg.b = 240
main_fg.r = 52
main_fg.g = 51
main_fg.b = 49
title.r = 16
title.g = 15
title.b = 15
hi_fg.r = 188
hi_fg.g = 82
hi_fg.b = 21
selected_bg.r = 230
selected_bg.g = 228
selected_bg.b = 217
selected_fg.r = 16
selected_fg.g = 15
selected_fg.b = 15
inactive_fg.r = 148
inactive_fg.g = 146
inactive_fg.b = 139
div_line.r = 148
div_line.g = 147
div_line.b = 140
graph_text.r = 111
graph_text.g = 110
graph_text.b = 105
menu_fg.r = 52
menu_fg.g = 51
menu_fg.b = 49
menu_selected_bg.r = 230
menu_selected_bg.g = 228
menu_selected_bg.b = 217
menu_selected_fg.r = 188
menu_selected_fg.g = 82
menu_selected_fg.b = 21

