name = "flexoki-light"

main_bg.r = 255
main_bg.g = 252
main_bg.b = 240
main_fg.r = 52
main_fg.g = 51
main_fg.b = 49
title.r = 16
title.g = 15
title.b = 15
hi_fg.r = 188
hi_fg.g = 82
hi_fg.b = 21
selected_bg.r = 230
selected_bg.g = 228
selected_bg.b = 217
selected_fg.r = 16
selected_fg.g = 15
selected_fg.b = 15
inactive_fg.r = 183
inactive_fg.g = 181
inactive_fg.b = 172
div_line.r = 206
div_line.g = 205
div_line.b = 195
graph_text.r = 111
graph_text.g = 110
graph_text.b = 105
meter_bg.r = 218
meter_bg.g = 216
meter_bg.b = 206
search_box.r = 32
search_box.g = 94
search_box.b = 166
log_box.r = 102
log_box.g = 128
log_box.b = 11
player_box.r = 36
player_box.g = 131
player_box.b = 123
menu_bg.r = 255
menu_bg.g = 252
menu_bg.b = 240
menu_fg.r = 52
menu_fg.g = 51
menu_fg.b = 49
menu_selected_bg.r = 230
menu_selected_bg.g = 228
menu_selected_bg.b = 217
menu_selected_fg.r = 188
menu_selected_fg.g = 82
menu_selected_fg.b = 21
gradient_start.r = 32
gradient_start.g = 94
gradient_start.b = 166
gradient_mid.r = 94
gradient_mid.g = 64
gradient_mid.b = 157
gradient_end.r = 175
gradient_end.g = 48
gradient_end.b = 41

