name = "flexoki-dark"

main_bg.r = 16
main_bg.g = 15
main_bg.b = 15
main_fg.r = 206
main_fg.g = 205
main_fg.b = 195
title.r = 255
title.g = 252
title.b = 240
hi_fg.r = 218
hi_fg.g = 112
hi_fg.b = 44
selected_bg.r = 64
selected_bg.g = 62
selected_bg.b = 60
selected_fg.r = 255
selected_fg.g = 252
selected_fg.b = 240
inactive_fg.r = 87
inactive_fg.g = 86
inactive_fg.b = 83
div_line.r = 64
div_line.g = 62
div_line.b = 60
graph_text.r = 135
graph_text.g = 133
graph_text.b = 128
meter_bg.r = 52
meter_bg.g = 51
meter_bg.b = 49
search_box.r = 67
search_box.g = 133
search_box.b = 190
log_box.r = 135
log_box.g = 154
log_box.b = 57
player_box.r = 58
player_box.g = 169
player_box.b = 159
menu_bg.r = 16
menu_bg.g = 15
menu_bg.b = 15
menu_fg.r = 206
menu_fg.g = 205
menu_fg.b = 195
menu_selected_bg.r = 64
menu_selected_bg.g = 62
menu_selected_bg.b = 60
menu_selected_fg.r = 218
menu_selected_fg.g = 112
menu_selected_fg.b = 44
gradient_start.r = 67
gradient_start.g = 133
gradient_start.b = 190
gradient_mid.r = 139
gradient_mid.g = 126
gradient_mid.b = 200
gradient_end.r = 209
gradient_end.g = 77
gradient_end.b = 65

