name = "gruvbox_dark"

main_bg.r = 29
main_bg.g = 32
main_bg.b = 33
main_fg.r = 168
main_fg.g = 153
main_fg.b = 132
title.r = 235
title.g = 219
title.b = 178
hi_fg.r = 215
hi_fg.g = 153
hi_fg.b = 33
selected_bg.r = 40
selected_bg.g = 40
selected_bg.b = 40
selected_fg.r = 250
selected_fg.g = 189
selected_fg.b = 47
inactive_fg.r = 106
inactive_fg.g = 106
inactive_fg.b = 106
div_line.r = 168
div_line.g = 153
div_line.b = 132
graph_text.r = 106
graph_text.g = 106
graph_text.b = 106
menu_fg.r = 168
menu_fg.g = 153
menu_fg.b = 132
menu_selected_bg.r = 40
menu_selected_bg.g = 40
menu_selected_bg.b = 40
menu_selected_fg.r = 215
menu_selected_fg.g = 153
menu_selected_fg.b = 33

