name = "gruvbox_dark"

main_bg.r = 29
main_bg.g = 32
main_bg.b = 33
main_fg.r = 168
main_fg.g = 153
main_fg.b = 132
title.r = 235
title.g = 219
title.b = 178
hi_fg.r = 215
hi_fg.g = 153
hi_fg.b = 33
selected_bg.r = 40
selected_bg.g = 40
selected_bg.b = 40
selected_fg.r = 250
selected_fg.g = 189
selected_fg.b = 47
inactive_fg.r = 40
inactive_fg.g = 40
inactive_fg.b = 40
div_line.r = 168
div_line.g = 153
div_line.b = 132
graph_text.r = 88
graph_text.g = 88
graph_text.b = 88
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 168
search_box.g = 153
search_box.b = 132
log_box.r = 168
log_box.g = 153
log_box.b = 132
player_box.r = 168
player_box.g = 153
player_box.b = 132
menu_bg.r = 29
menu_bg.g = 32
menu_bg.b = 33
menu_fg.r = 168
menu_fg.g = 153
menu_fg.b = 132
menu_selected_bg.r = 40
menu_selected_bg.g = 40
menu_selected_bg.b = 40
menu_selected_fg.r = 215
menu_selected_fg.g = 153
menu_selected_fg.b = 33
gradient_start.r = 69
gradient_start.g = 133
gradient_start.b = 136
gradient_mid.r = 211
gradient_mid.g = 134
gradient_mid.b = 155
gradient_end.r = 251
gradient_end.g = 67
gradient_end.b = 148

