name = "gruvbox_light"

main_bg.r = 251
main_bg.g = 241
main_bg.b = 199
main_fg.r = 60
main_fg.g = 56
main_fg.b = 54
title.r = 60
title.g = 56
title.b = 54
hi_fg.r = 204
hi_fg.g = 36
hi_fg.b = 29
selected_bg.r = 242
selected_bg.g = 229
selected_bg.b = 188
selected_fg.r = 143
selected_fg.g = 63
selected_fg.b = 113
inactive_fg.r = 148
inactive_fg.g = 138
inactive_fg.b = 112
div_line.r = 150
div_line.g = 137
div_line.b = 118
graph_text.r = 150
graph_text.g = 137
graph_text.b = 118
menu_fg.r = 60
menu_fg.g = 56
menu_fg.b = 54
menu_selected_bg.r = 242
menu_selected_bg.g = 229
menu_selected_bg.b = 188
menu_selected_fg.r = 204
menu_selected_fg.g = 36
menu_selected_fg.b = 29

