name = "gruvbox_material_dark"

main_bg.r = 40
main_bg.g = 40
main_bg.b = 40
main_fg.r = 212
main_fg.g = 190
main_fg.b = 152
title.r = 212
title.g = 190
title.b = 152
hi_fg.r = 234
hi_fg.g = 105
hi_fg.b = 98
selected_bg.r = 216
selected_bg.g = 166
selected_bg.b = 87
selected_fg.r = 40
selected_fg.g = 40
selected_fg.b = 40
inactive_fg.r = 40
inactive_fg.g = 40
inactive_fg.b = 40
div_line.r = 124
div_line.g = 111
div_line.b = 100
graph_text.r = 102
graph_text.g = 92
graph_text.b = 84
menu_fg.r = 212
menu_fg.g = 190
menu_fg.b = 152
menu_selected_bg.r = 216
menu_selected_bg.g = 166
menu_selected_bg.b = 87
menu_selected_fg.r = 234
menu_selected_fg.g = 105
menu_selected_fg.b = 98

