name = "horizon"

main_bg.r = 28
main_bg.g = 30
main_bg.b = 38
main_fg.r = 248
main_fg.g = 248
main_fg.b = 242
title.r = 248
title.g = 248
title.b = 242
hi_fg.r = 184
hi_fg.g = 119
hi_fg.b = 219
selected_bg.r = 40
selected_bg.g = 43
selected_bg.b = 55
selected_fg.r = 248
selected_fg.g = 248
selected_fg.b = 242
inactive_fg.r = 39
inactive_fg.g = 46
inactive_fg.b = 51
div_line.r = 39
div_line.g = 46
div_line.b = 51
graph_text.r = 248
graph_text.g = 248
graph_text.b = 242
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 184
search_box.g = 119
search_box.b = 219
log_box.r = 39
log_box.g = 215
log_box.b = 150
player_box.r = 37
player_box.g = 178
player_box.b = 188
menu_bg.r = 28
menu_bg.g = 30
menu_bg.b = 38
menu_fg.r = 248
menu_fg.g = 248
menu_fg.b = 242
menu_selected_bg.r = 40
menu_selected_bg.g = 43
menu_selected_bg.b = 55
menu_selected_fg.r = 184
menu_selected_fg.g = 119
menu_selected_fg.b = 219
gradient_start.r = 39
gradient_start.g = 215
gradient_start.b = 150
gradient_mid.r = 250
gradient_mid.g = 194
gradient_mid.b = 154
gradient_end.r = 233
gradient_end.g = 86
gradient_end.b = 120

