name = "horizon"

main_bg.r = 28
main_bg.g = 30
main_bg.b = 38
main_fg.r = 248
main_fg.g = 248
main_fg.b = 242
title.r = 248
title.g = 248
title.b = 242
hi_fg.r = 184
hi_fg.g = 119
hi_fg.b = 219
selected_bg.r = 40
selected_bg.g = 43
selected_bg.b = 55
selected_fg.r = 248
selected_fg.g = 248
selected_fg.b = 242
inactive_fg.r = 39
inactive_fg.g = 46
inactive_fg.b = 51
div_line.r = 39
div_line.g = 46
div_line.b = 51
graph_text.r = 248
graph_text.g = 248
graph_text.b = 242
menu_fg.r = 248
menu_fg.g = 248
menu_fg.b = 242
menu_selected_bg.r = 40
menu_selected_bg.g = 43
menu_selected_bg.b = 55
menu_selected_fg.r = 184
menu_selected_fg.g = 119
menu_selected_fg.b = 219

