name = "HotPurpleTrafficLight"

main_bg.r = 0
main_bg.g = 0
main_bg.b = 0
main_fg.r = 209
main_fg.g = 209
main_fg.b = 224
title.r = 209
title.g = 209
title.b = 224
hi_fg.r = 153
hi_fg.g = 51
hi_fg.b = 255
selected_bg.r = 102
selected_bg.g = 102
selected_bg.b = 255
selected_fg.r = 209
selected_fg.g = 209
selected_fg.b = 224
inactive_fg.r = 153
inactive_fg.g = 153
inactive_fg.b = 255
div_line.r = 77
div_line.g = 77
div_line.b = 255
graph_text.r = 153
graph_text.g = 51
graph_text.b = 255
meter_bg.r = 77
meter_bg.g = 77
meter_bg.b = 255
search_box.r = 166
search_box.g = 77
search_box.b = 255
log_box.r = 166
log_box.g = 77
log_box.b = 255
player_box.r = 166
player_box.g = 77
player_box.b = 255
menu_bg.r = 0
menu_bg.g = 0
menu_bg.b = 0
menu_fg.r = 209
menu_fg.g = 209
menu_fg.b = 224
menu_selected_bg.r = 102
menu_selected_bg.g = 102
menu_selected_bg.b = 255
menu_selected_fg.r = 153
menu_selected_fg.g = 51
menu_selected_fg.b = 255
gradient_start.r = 0
gradient_start.g = 255
gradient_start.b = 0
gradient_mid.r = 255
gradient_mid.g = 153
gradient_mid.b = 51
gradient_end.r = 255
gradient_end.g = 0
gradient_end.b = 0

