name = "HotPurpleTrafficLight"

main_bg.r = 0
main_bg.g = 0
main_bg.b = 0
main_fg.r = 209
main_fg.g = 209
main_fg.b = 224
title.r = 209
title.g = 209
title.b = 224
hi_fg.r = 153
hi_fg.g = 51
hi_fg.b = 255
selected_bg.r = 102
selected_bg.g = 102
selected_bg.b = 255
selected_fg.r = 209
selected_fg.g = 209
selected_fg.b = 224
inactive_fg.r = 153
inactive_fg.g = 153
inactive_fg.b = 255
div_line.r = 77
div_line.g = 77
div_line.b = 255
graph_text.r = 153
graph_text.g = 51
graph_text.b = 255
menu_fg.r = 209
menu_fg.g = 209
menu_fg.b = 224
menu_selected_bg.r = 102
menu_selected_bg.g = 102
menu_selected_bg.b = 255
menu_selected_fg.r = 153
menu_selected_fg.g = 51
menu_selected_fg.b = 255

