name = "kanagawa-lotus"

main_bg.r = 242
main_bg.g = 236
main_bg.b = 188
main_fg.r = 84
main_fg.g = 84
main_fg.b = 100
title.r = 84
title.g = 84
title.b = 100
hi_fg.r = 200
hi_fg.g = 64
hi_fg.b = 83
selected_bg.r = 201
selected_bg.g = 203
selected_bg.b = 209
selected_fg.r = 67
selected_fg.g = 67
selected_fg.b = 108
inactive_fg.r = 136
inactive_fg.g = 135
inactive_fg.b = 126
div_line.r = 136
div_line.g = 135
div_line.b = 126
graph_text.r = 104
graph_text.g = 139
graph_text.b = 156
menu_fg.r = 84
menu_fg.g = 84
menu_fg.b = 100
menu_selected_bg.r = 201
menu_selected_bg.g = 203
menu_selected_bg.b = 209
menu_selected_fg.r = 200
menu_selected_fg.g = 64
menu_selected_fg.b = 83

