name = "kanagawa-wave"

main_bg.r = 22
main_bg.g = 22
main_bg.b = 29
main_fg.r = 220
main_fg.g = 215
main_fg.b = 186
title.r = 220
title.g = 215
title.b = 186
hi_fg.r = 195
hi_fg.g = 64
hi_fg.b = 67
selected_bg.r = 34
selected_bg.g = 50
selected_bg.b = 73
selected_fg.r = 220
selected_fg.g = 165
selected_fg.b = 97
inactive_fg.r = 114
inactive_fg.g = 113
inactive_fg.b = 105
div_line.r = 114
div_line.g = 113
div_line.b = 105
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 114
search_box.g = 113
search_box.b = 105
log_box.r = 114
log_box.g = 113
log_box.b = 105
player_box.r = 114
player_box.g = 113
player_box.b = 105
menu_bg.r = 22
menu_bg.g = 22
menu_bg.b = 29
menu_fg.r = 220
menu_fg.g = 215
menu_fg.b = 186
menu_selected_bg.r = 34
menu_selected_bg.g = 50
menu_selected_bg.b = 73
menu_selected_fg.r = 195
menu_selected_fg.g = 64
menu_selected_fg.b = 67
gradient_start.r = 152
gradient_start.g = 187
gradient_start.b = 108
gradient_mid.r = 220
gradient_mid.g = 165
gradient_mid.b = 97
gradient_end.r = 232
gradient_end.g = 36
gradient_end.b = 36

