name = "kanagawa-lotus"

main_bg.r = 242
main_bg.g = 236
main_bg.b = 188
main_fg.r = 84
main_fg.g = 84
main_fg.b = 100
title.r = 84
title.g = 84
title.b = 100
hi_fg.r = 200
hi_fg.g = 64
hi_fg.b = 83
selected_bg.r = 201
selected_bg.g = 203
selected_bg.b = 209
selected_fg.r = 67
selected_fg.g = 67
selected_fg.b = 108
inactive_fg.r = 138
inactive_fg.g = 137
inactive_fg.b = 128
div_line.r = 138
div_line.g = 137
div_line.b = 128
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 138
search_box.g = 137
search_box.b = 128
log_box.r = 138
log_box.g = 137
log_box.b = 128
player_box.r = 138
player_box.g = 137
player_box.b = 128
menu_bg.r = 242
menu_bg.g = 236
menu_bg.b = 188
menu_fg.r = 84
menu_fg.g = 84
menu_fg.b = 100
menu_selected_bg.r = 201
menu_selected_bg.g = 203
menu_selected_bg.b = 209
menu_selected_fg.r = 200
menu_selected_fg.g = 64
menu_selected_fg.b = 83
gradient_start.r = 110
gradient_start.g = 145
gradient_start.b = 95
gradient_mid.r = 204
gradient_mid.g = 109
gradient_mid.b = 0
gradient_end.r = 215
gradient_end.g = 71
gradient_end.b = 75

