name = "kanagawa-dragon"

main_bg.r = 24
main_bg.g = 22
main_bg.b = 22
main_fg.r = 197
main_fg.g = 201
main_fg.b = 197
title.r = 197
title.g = 201
title.b = 197
hi_fg.r = 196
hi_fg.g = 116
hi_fg.b = 110
selected_bg.r = 40
selected_bg.g = 39
selected_bg.b = 39
selected_fg.r = 196
selected_fg.g = 178
selected_fg.b = 138
inactive_fg.r = 122
inactive_fg.g = 131
inactive_fg.b = 130
div_line.r = 122
div_line.g = 131
div_line.b = 130
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 122
search_box.g = 131
search_box.b = 130
log_box.r = 122
log_box.g = 131
log_box.b = 130
player_box.r = 122
player_box.g = 131
player_box.b = 130
menu_bg.r = 24
menu_bg.g = 22
menu_bg.b = 22
menu_fg.r = 197
menu_fg.g = 201
menu_fg.b = 197
menu_selected_bg.r = 40
menu_selected_bg.g = 39
menu_selected_bg.b = 39
menu_selected_fg.r = 196
menu_selected_fg.g = 116
menu_selected_fg.b = 110
gradient_start.r = 138
gradient_start.g = 154
gradient_start.b = 123
gradient_mid.r = 182
gradient_mid.g = 146
gradient_mid.b = 123
gradient_end.r = 196
gradient_end.g = 116
gradient_end.b = 110

