name = "kanagawa-wave"

main_bg.r = 22
main_bg.g = 22
main_bg.b = 29
main_fg.r = 220
main_fg.g = 215
main_fg.b = 186
title.r = 220
title.g = 215
title.b = 186
hi_fg.r = 195
hi_fg.g = 64
hi_fg.b = 67
selected_bg.r = 34
selected_bg.g = 50
selected_bg.b = 73
selected_fg.r = 220
selected_fg.g = 165
selected_fg.b = 97
inactive_fg.r = 114
inactive_fg.g = 113
inactive_fg.b = 105
div_line.r = 114
div_line.g = 113
div_line.b = 105
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
menu_fg.r = 220
menu_fg.g = 215
menu_fg.b = 186
menu_selected_bg.r = 34
menu_selected_bg.g = 50
menu_selected_bg.b = 73
menu_selected_fg.r = 195
menu_selected_fg.g = 64
menu_selected_fg.b = 67

