name = "kyli0x"

main_bg.r = 34
main_bg.g = 34
main_bg.b = 34
main_fg.r = 232
main_fg.g = 246
main_fg.b = 245
title.r = 232
title.g = 246
title.b = 245
hi_fg.r = 33
hi_fg.g = 214
hi_fg.b = 201
selected_bg.r = 26
selected_bg.g = 171
selected_bg.b = 160
selected_fg.r = 232
selected_fg.g = 246
selected_fg.b = 245
inactive_fg.r = 94
inactive_fg.g = 196
inactive_fg.b = 188
div_line.r = 128
div_line.g = 99
div_line.b = 142
graph_text.r = 186
graph_text.g = 26
graph_text.b = 132
menu_fg.r = 232
menu_fg.g = 246
menu_fg.b = 245
menu_selected_bg.r = 26
menu_selected_bg.g = 171
menu_selected_bg.b = 160
menu_selected_fg.r = 33
menu_selected_fg.g = 214
menu_selected_fg.b = 201

