name = "kyli0x"

main_bg.r = 34
main_bg.g = 34
main_bg.b = 34
main_fg.r = 232
main_fg.g = 246
main_fg.b = 245
title.r = 232
title.g = 246
title.b = 245
hi_fg.r = 33
hi_fg.g = 214
hi_fg.b = 201
selected_bg.r = 26
selected_bg.g = 171
selected_bg.b = 160
selected_fg.r = 232
selected_fg.g = 246
selected_fg.b = 245
inactive_fg.r = 94
inactive_fg.g = 196
inactive_fg.b = 188
div_line.r = 128
div_line.g = 99
div_line.b = 142
graph_text.r = 186
graph_text.g = 26
graph_text.b = 132
meter_bg.r = 94
meter_bg.g = 196
meter_bg.b = 188
search_box.r = 212
search_box.g = 134
search_box.b = 212
log_box.r = 212
log_box.g = 134
log_box.b = 212
player_box.r = 212
player_box.g = 134
player_box.b = 212
menu_bg.r = 34
menu_bg.g = 34
menu_bg.b = 34
menu_fg.r = 232
menu_fg.g = 246
menu_fg.b = 245
menu_selected_bg.r = 26
menu_selected_bg.g = 171
menu_selected_bg.b = 160
menu_selected_fg.r = 33
menu_selected_fg.g = 214
menu_selected_fg.b = 201
gradient_start.r = 33
gradient_start.g = 214
gradient_start.b = 201
gradient_mid.r = 26
gradient_mid.g = 171
gradient_mid.b = 160
gradient_end.r = 94
gradient_end.g = 196
gradient_end.b = 188

