name = "monokai"

main_bg.r = 6
main_bg.g = 6
main_bg.b = 4
main_fg.r = 248
main_fg.g = 248
main_fg.b = 242
title.r = 248
title.g = 248
title.b = 242
hi_fg.r = 249
hi_fg.g = 38
hi_fg.b = 114
selected_bg.r = 122
selected_bg.g = 17
selected_bg.b = 55
selected_fg.r = 248
selected_fg.g = 248
selected_fg.b = 242
inactive_fg.r = 95
inactive_fg.g = 92
inactive_fg.b = 76
div_line.r = 95
div_line.g = 92
div_line.b = 76
graph_text.r = 121
graph_text.g = 118
graph_text.b = 103
menu_fg.r = 248
menu_fg.g = 248
menu_fg.b = 242
menu_selected_bg.r = 122
menu_selected_bg.g = 17
menu_selected_bg.b = 55
menu_selected_fg.r = 249
menu_selected_fg.g = 38
menu_selected_fg.b = 114

