name = "monokai"

main_bg.r = 6
main_bg.g = 6
main_bg.b = 4
main_fg.r = 248
main_fg.g = 248
main_fg.b = 242
title.r = 248
title.g = 248
title.b = 242
hi_fg.r = 249
hi_fg.g = 38
hi_fg.b = 114
selected_bg.r = 122
selected_bg.g = 17
selected_bg.b = 55
selected_fg.r = 248
selected_fg.g = 248
selected_fg.b = 242
inactive_fg.r = 89
inactive_fg.g = 86
inactive_fg.b = 71
div_line.r = 89
div_line.g = 86
div_line.b = 71
graph_text.r = 121
graph_text.g = 118
graph_text.b = 103
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 117
search_box.g = 113
search_box.b = 94
log_box.r = 117
log_box.g = 113
log_box.b = 94
player_box.r = 117
player_box.g = 113
player_box.b = 94
menu_bg.r = 6
menu_bg.g = 6
menu_bg.b = 4
menu_fg.r = 248
menu_fg.g = 248
menu_fg.b = 242
menu_selected_bg.r = 122
menu_selected_bg.g = 17
menu_selected_bg.b = 55
menu_selected_fg.r = 249
menu_selected_fg.g = 38
menu_selected_fg.b = 114
gradient_start.r = 121
gradient_start.g = 118
gradient_start.b = 183
gradient_mid.r = 216
gradient_mid.g = 184
gradient_mid.b = 178
gradient_end.r = 249
gradient_end.g = 38
gradient_end.b = 114

