name = "noctalia"

main_bg.r = 20
main_bg.g = 19
main_bg.b = 24
main_fg.r = 230
main_fg.g = 225
main_fg.b = 233
title.r = 230
title.g = 225
title.b = 233
hi_fg.r = 204
hi_fg.g = 189
hi_fg.b = 255
selected_bg.r = 72
selected_bg.g = 69
selected_bg.b = 78
selected_fg.r = 202
selected_fg.g = 196
selected_fg.b = 207
inactive_fg.r = 147
inactive_fg.g = 143
inactive_fg.b = 153
div_line.r = 72
div_line.g = 69
div_line.b = 78
graph_text.r = 202
graph_text.g = 195
graph_text.b = 220
meter_bg.r = 72
meter_bg.g = 69
meter_bg.b = 78
search_box.r = 204
search_box.g = 189
search_box.b = 255
log_box.r = 238
log_box.g = 184
log_box.b = 202
player_box.r = 204
player_box.g = 189
player_box.b = 255
menu_bg.r = 20
menu_bg.g = 19
menu_bg.b = 24
menu_fg.r = 202
menu_fg.g = 196
menu_fg.b = 207
menu_selected_bg.r = 72
menu_selected_bg.g = 69
menu_selected_bg.b = 78
menu_selected_fg.r = 204
menu_selected_fg.g = 189
menu_selected_fg.b = 255
gradient_start.r = 204
gradient_start.g = 189
gradient_start.b = 255
gradient_mid.r = 238
gradient_mid.g = 184
gradient_mid.b = 202
gradient_end.r = 202
gradient_end.g = 195
gradient_end.b = 220
