name = "onedark"

main_bg.r = 40
main_bg.g = 44
main_bg.b = 52
main_fg.r = 171
main_fg.g = 178
main_fg.b = 191
title.r = 171
title.g = 178
title.b = 191
hi_fg.r = 97
hi_fg.g = 175
hi_fg.b = 239
selected_bg.r = 44
selected_bg.g = 49
selected_bg.b = 60
selected_fg.r = 171
selected_fg.g = 178
selected_fg.b = 191
inactive_fg.r = 92
inactive_fg.g = 99
inactive_fg.b = 112
div_line.r = 92
div_line.g = 99
div_line.b = 112
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 92
search_box.g = 99
search_box.b = 112
log_box.r = 92
log_box.g = 99
log_box.b = 112
player_box.r = 92
player_box.g = 99
player_box.b = 112
menu_bg.r = 40
menu_bg.g = 44
menu_bg.b = 52
menu_fg.r = 171
menu_fg.g = 178
menu_fg.b = 191
menu_selected_bg.r = 44
menu_selected_bg.g = 49
menu_selected_bg.b = 60
menu_selected_fg.r = 97
menu_selected_fg.g = 175
menu_selected_fg.b = 239
gradient_start.r = 152
gradient_start.g = 195
gradient_start.b = 121
gradient_mid.r = 229
gradient_mid.g = 192
gradient_mid.b = 123
gradient_end.r = 224
gradient_end.g = 108
gradient_end.b = 117

