name = "onedark"

main_bg.r = 40
main_bg.g = 44
main_bg.b = 52
main_fg.r = 171
main_fg.g = 178
main_fg.b = 191
title.r = 171
title.g = 178
title.b = 191
hi_fg.r = 97
hi_fg.g = 175
hi_fg.b = 239
selected_bg.r = 44
selected_bg.g = 49
selected_bg.b = 60
selected_fg.r = 171
selected_fg.g = 178
selected_fg.b = 191
inactive_fg.r = 92
inactive_fg.g = 99
inactive_fg.b = 112
div_line.r = 92
div_line.g = 99
div_line.b = 112
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
menu_fg.r = 171
menu_fg.g = 178
menu_fg.b = 191
menu_selected_bg.r = 44
menu_selected_bg.g = 49
menu_selected_bg.b = 60
menu_selected_fg.r = 97
menu_selected_fg.g = 175
menu_selected_fg.b = 239

