name = "orange"

main_bg.r = 136
main_bg.g = 136
main_bg.b = 136
main_fg.r = 255
main_fg.g = 165
main_fg.b = 0
title.r = 255
title.g = 165
title.b = 0
hi_fg.r = 255
hi_fg.g = 204
hi_fg.b = 102
selected_bg.r = 255
selected_bg.g = 165
selected_bg.b = 0
selected_fg.r = 0
selected_fg.g = 0
selected_fg.b = 0
inactive_fg.r = 77
inactive_fg.g = 50
inactive_fg.b = 0
div_line.r = 51
div_line.g = 33
div_line.b = 0
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 255
search_box.g = 165
search_box.b = 0
log_box.r = 255
log_box.g = 165
log_box.b = 0
player_box.r = 255
player_box.g = 165
player_box.b = 0
menu_bg.r = 136
menu_bg.g = 136
menu_bg.b = 136
menu_fg.r = 255
menu_fg.g = 165
menu_fg.b = 0
menu_selected_bg.r = 255
menu_selected_bg.g = 165
menu_selected_bg.b = 0
menu_selected_fg.r = 255
menu_selected_fg.g = 204
menu_selected_fg.b = 102
gradient_start.r = 153
gradient_start.g = 99
gradient_start.b = 0
gradient_mid.r = 38
gradient_mid.g = 166
gradient_mid.b = 154
gradient_end.r = 255
gradient_end.g = 165
gradient_end.b = 0

