name = "paper"

main_bg.r = 242
main_bg.g = 238
main_bg.b = 222
main_fg.r = 108
main_fg.g = 108
main_fg.b = 108
title.r = 136
title.g = 136
title.b = 136
hi_fg.r = 204
hi_fg.g = 62
hi_fg.b = 40
selected_bg.r = 216
selected_bg.g = 213
selected_bg.b = 199
selected_fg.r = 92
selected_fg.g = 92
selected_fg.b = 92
inactive_fg.r = 139
inactive_fg.g = 137
inactive_fg.b = 128
div_line.r = 136
div_line.g = 136
div_line.b = 136
graph_text.r = 107
graph_text.g = 142
graph_text.b = 160
menu_fg.r = 136
menu_fg.g = 136
menu_fg.b = 136
menu_selected_bg.r = 216
menu_selected_bg.g = 213
menu_selected_bg.b = 199
menu_selected_fg.r = 204
menu_selected_fg.g = 62
menu_selected_fg.b = 40

