name = "solarized_light"

main_bg.r = 253
main_bg.g = 246
main_bg.b = 227
main_fg.r = 88
main_fg.g = 110
main_fg.b = 117
title.r = 0
title.g = 43
title.b = 54
hi_fg.r = 181
hi_fg.g = 137
hi_fg.b = 0
selected_bg.r = 238
selected_bg.g = 232
selected_bg.b = 213
selected_fg.r = 181
selected_fg.g = 137
selected_fg.b = 0
inactive_fg.r = 238
inactive_fg.g = 232
inactive_fg.b = 213
div_line.r = 147
div_line.g = 161
div_line.b = 161
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 147
search_box.g = 161
search_box.b = 161
log_box.r = 147
log_box.g = 161
log_box.b = 161
player_box.r = 147
player_box.g = 161
player_box.b = 161
menu_bg.r = 253
menu_bg.g = 246
menu_bg.b = 227
menu_fg.r = 88
menu_fg.g = 110
menu_fg.b = 117
menu_selected_bg.r = 238
menu_selected_bg.g = 232
menu_selected_bg.b = 213
menu_selected_fg.r = 181
menu_selected_fg.g = 137
menu_selected_fg.b = 0
gradient_start.r = 38
gradient_start.g = 139
gradient_start.b = 210
gradient_mid.r = 204
gradient_mid.g = 181
gradient_mid.b = 247
gradient_end.r = 252
gradient_end.g = 83
gradient_end.b = 120

