name = "solarized_dark"

main_bg.r = 0
main_bg.g = 43
main_bg.b = 54
main_fg.r = 238
main_fg.g = 232
main_fg.b = 213
title.r = 253
title.g = 246
title.b = 227
hi_fg.r = 181
hi_fg.g = 137
hi_fg.b = 0
selected_bg.r = 7
selected_bg.g = 54
selected_bg.b = 66
selected_fg.r = 214
selected_fg.g = 162
selected_fg.b = 0
inactive_fg.r = 7
inactive_fg.g = 54
inactive_fg.b = 66
div_line.r = 88
div_line.g = 110
div_line.b = 117
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 88
search_box.g = 110
search_box.b = 117
log_box.r = 88
log_box.g = 110
log_box.b = 117
player_box.r = 88
player_box.g = 110
player_box.b = 117
menu_bg.r = 0
menu_bg.g = 43
menu_bg.b = 54
menu_fg.r = 238
menu_fg.g = 232
menu_fg.b = 213
menu_selected_bg.r = 7
menu_selected_bg.g = 54
menu_selected_bg.b = 66
menu_selected_fg.r = 181
menu_selected_fg.g = 137
menu_selected_fg.b = 0
gradient_start.r = 38
gradient_start.g = 139
gradient_start.b = 210
gradient_mid.r = 204
gradient_mid.g = 181
gradient_mid.b = 247
gradient_end.r = 252
gradient_end.g = 83
gradient_end.b = 120

