name = "solarized_light"

main_bg.r = 253
main_bg.g = 246
main_bg.b = 227
main_fg.r = 88
main_fg.g = 110
main_fg.b = 117
title.r = 0
title.g = 43
title.b = 54
hi_fg.r = 180
hi_fg.g = 136
hi_fg.b = 0
selected_bg.r = 238
selected_bg.g = 232
selected_bg.b = 213
selected_fg.r = 132
selected_fg.g = 100
selected_fg.b = 0
inactive_fg.r = 146
inactive_fg.g = 142
inactive_fg.b = 131
div_line.r = 132
div_line.g = 145
div_line.b = 145
graph_text.r = 111
graph_text.g = 148
graph_text.b = 167
menu_fg.r = 88
menu_fg.g = 110
menu_fg.b = 117
menu_selected_bg.r = 238
menu_selected_bg.g = 232
menu_selected_bg.b = 213
menu_selected_fg.r = 181
menu_selected_fg.g = 137
menu_selected_fg.b = 0

