name = "tokyo-night"

main_bg.r = 26
main_bg.g = 27
main_bg.b = 38
main_fg.r = 207
main_fg.g = 201
main_fg.b = 194
title.r = 207
title.g = 201
title.b = 194
hi_fg.r = 125
hi_fg.g = 207
hi_fg.b = 255
selected_bg.r = 65
selected_bg.g = 72
selected_bg.b = 104
selected_fg.r = 207
selected_fg.g = 201
selected_fg.b = 194
inactive_fg.r = 86
inactive_fg.g = 95
inactive_fg.b = 137
div_line.r = 86
div_line.g = 95
div_line.b = 137
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
menu_fg.r = 207
menu_fg.g = 201
menu_fg.b = 194
menu_selected_bg.r = 65
menu_selected_bg.g = 72
menu_selected_bg.b = 104
menu_selected_fg.r = 125
menu_selected_fg.g = 207
menu_selected_fg.b = 255

