name = "tomorrow-night"

main_bg.r = 29
main_bg.g = 31
main_bg.b = 33
main_fg.r = 197
main_fg.g = 200
main_fg.b = 198
title.r = 197
title.g = 200
title.b = 198
hi_fg.r = 129
hi_fg.g = 190
hi_fg.b = 183
selected_bg.r = 40
selected_bg.g = 42
selected_bg.b = 46
selected_fg.r = 197
selected_fg.g = 200
selected_fg.b = 198
inactive_fg.r = 99
inactive_fg.g = 106
inactive_fg.b = 117
div_line.r = 129
div_line.g = 162
div_line.b = 190
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
menu_fg.r = 197
menu_fg.g = 200
menu_fg.b = 198
menu_selected_bg.r = 40
menu_selected_bg.g = 42
menu_selected_bg.b = 46
menu_selected_fg.r = 129
menu_selected_fg.g = 190
menu_selected_fg.b = 183

