name = "tomorrow-night"

main_bg.r = 29
main_bg.g = 31
main_bg.b = 33
main_fg.r = 197
main_fg.g = 200
main_fg.b = 198
title.r = 197
title.g = 200
title.b = 198
hi_fg.r = 129
hi_fg.g = 190
hi_fg.b = 183
selected_bg.r = 40
selected_bg.g = 42
selected_bg.b = 46
selected_fg.r = 197
selected_fg.g = 200
selected_fg.b = 198
inactive_fg.r = 55
inactive_fg.g = 59
inactive_fg.b = 65
div_line.r = 129
div_line.g = 162
div_line.b = 190
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 129
search_box.g = 162
search_box.b = 190
log_box.r = 129
log_box.g = 162
log_box.b = 190
player_box.r = 129
player_box.g = 162
player_box.b = 190
menu_bg.r = 29
menu_bg.g = 31
menu_bg.b = 33
menu_fg.r = 197
menu_fg.g = 200
menu_fg.b = 198
menu_selected_bg.r = 40
menu_selected_bg.g = 42
menu_selected_bg.b = 46
menu_selected_fg.r = 129
menu_selected_fg.g = 190
menu_selected_fg.b = 183
gradient_start.r = 181
gradient_start.g = 189
gradient_start.b = 104
gradient_mid.r = 240
gradient_mid.g = 198
gradient_mid.b = 116
gradient_end.r = 204
gradient_end.g = 102
gradient_end.b = 102

