name = "twilight"

main_bg.r = 20
main_bg.g = 20
main_bg.b = 20
main_fg.r = 167
main_fg.g = 167
main_fg.b = 167
title.r = 218
title.g = 208
title.b = 133
hi_fg.r = 207
hi_fg.g = 106
hi_fg.b = 76
selected_bg.r = 62
selected_bg.g = 62
selected_bg.b = 62
selected_fg.r = 139
selected_fg.g = 152
selected_fg.b = 171
inactive_fg.r = 130
inactive_fg.g = 130
inactive_fg.b = 130
div_line.r = 73
div_line.g = 73
div_line.b = 73
graph_text.r = 197
graph_text.g = 175
graph_text.b = 117
meter_bg.r = 62
meter_bg.g = 62
meter_bg.b = 62
search_box.r = 143
search_box.g = 157
search_box.b = 106
log_box.r = 155
log_box.g = 112
log_box.b = 63
player_box.r = 207
player_box.g = 106
player_box.b = 76
menu_bg.r = 20
menu_bg.g = 20
menu_bg.b = 20
menu_fg.r = 167
menu_fg.g = 167
menu_fg.b = 167
menu_selected_bg.r = 62
menu_selected_bg.g = 62
menu_selected_bg.b = 62
menu_selected_fg.r = 207
menu_selected_fg.g = 106
menu_selected_fg.b = 76
gradient_start.r = 143
gradient_start.g = 157
gradient_start.b = 106
gradient_mid.r = 249
gradient_mid.g = 238
gradient_mid.b = 152
gradient_end.r = 207
gradient_end.g = 106
gradient_end.b = 76

