name = "whiteout"

main_bg.r = 136
main_bg.g = 136
main_bg.b = 136
main_fg.r = 136
main_fg.g = 136
main_fg.b = 136
title.r = 136
title.g = 136
title.b = 136
hi_fg.r = 40
hi_fg.g = 77
hi_fg.b = 117
selected_bg.r = 21
selected_bg.g = 40
selected_bg.b = 61
selected_fg.r = 136
selected_fg.g = 136
selected_fg.b = 136
inactive_fg.r = 136
inactive_fg.g = 136
inactive_fg.b = 136
div_line.r = 136
div_line.g = 136
div_line.b = 136
graph_text.r = 120
graph_text.g = 160
graph_text.b = 180
meter_bg.r = 15
meter_bg.g = 30
meter_bg.b = 50
search_box.r = 26
search_box.g = 54
search_box.b = 30
log_box.r = 61
log_box.g = 60
log_box.b = 20
player_box.r = 59
player_box.g = 21
player_box.b = 21
menu_bg.r = 136
menu_bg.g = 136
menu_bg.b = 136
menu_fg.r = 136
menu_fg.g = 136
menu_fg.b = 136
menu_selected_bg.r = 21
menu_selected_bg.g = 40
menu_selected_bg.b = 61
menu_selected_fg.r = 40
menu_selected_fg.g = 77
menu_selected_fg.b = 117
gradient_start.r = 24
gradient_start.g = 69
gradient_start.b = 103
gradient_mid.r = 18
gradient_mid.g = 44
gradient_mid.b = 135
gradient_end.r = 158
gradient_end.g = 0
gradient_end.b = 97

