/// MPV stderr filter: true when the line is worth showing in the log.
pub fn should_log(line: &str) -> bool {
    let low = line.to_lowercase();
    [
        "vo:",
        "ao:",
        "av:",
        "video:",
        "audio:",
        "cache",
        "hwdec",
        "vaapi",
        "vdpau",
        "nvdec",
        "cuda",
        "drm",
        "duration:",
        "playing:",
        "exiting",
        "resume",
        "track",
        "tag:",
        "kbps",
        "fps",
        "h264",
        "h265",
        "hevc",
        "av1",
        "vp9",
        "aac",
        "ac3",
        "opus",
        "flac",
        "passthrough",
        "format",
        "video output",
        "audio output",
        "pix_fmt",
        "backend",
        "1056",
        "1920",
        "1280",
    ]
    .iter()
    .any(|k| low.contains(k))
}
